apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: service1-tls
  namespace: default
spec:
  secretName: service1-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - Matorg Inc
  commonName: matorg.com
  dnsNames:
    - matorg.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
