apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cert-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io
