apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: southamerica-east1-docker.pkg.dev/hallowed-object-458420-q9/fast-api/service1:latest
        ports:
        - containerPort: 80
