piVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: matorg.com
      http:
        paths:
          - path: /service1/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service1
                port:
                  number: 80
