apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: matorg.com
      http:
        paths:
          - path: /service1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: service1
                port:
                  number: 80
  tls:
    - hosts:
        - matorg.com
      secretName: service1-tls
